# Generated by Django 4.1.3 on 2022-12-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('mi', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('avatar_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
